In [2]:
import pandas

df_8 = pandas.read_csv("data.txt")
df_8

   2021-09-22 01:15:00  $2.03  $69.83  0.0344  34.40  ADA    -15%  BUY
0  2021-09-23 01:00:00  $2.26  $10.84  0.0048    4.8  ADA   13.7%  BUY
1  2021-09-24 01:00:00  $2.33  $10.94  0.0047    4.7  ADA   3.15%  BUY
2  2021-09-25 01:00:00  $2.28  $10.94  0.0048    4.8  ADA   -2.1%  BUY
3  2021-09-26 01:00:00  $2.27  $10.88  0.0048    4.8  ADA  -1.18%  BUY
4  2021-09-27 01:00:00  $2.25  $10.78  0.0048    4.8  ADA   -1.1%  BUY
5  2021-09-28 01:00:00  $2.15  $10.94  0.0051    5.1  ADA  -4.45%  BUY

In [4]:
df_8.columns = ["id", "address", "city", "zip", "country", "name", "employees", "dogshit"]
df_8

                    id address    city     zip  country name employees dogshit
0  2021-09-23 01:00:00   $2.26  $10.84  0.0048      4.8  ADA     13.7%     BUY
1  2021-09-24 01:00:00   $2.33  $10.94  0.0047      4.7  ADA     3.15%     BUY
2  2021-09-25 01:00:00   $2.28  $10.94  0.0048      4.8  ADA     -2.1%     BUY
3  2021-09-26 01:00:00   $2.27  $10.88  0.0048      4.8  ADA    -1.18%     BUY
4  2021-09-27 01:00:00   $2.25  $10.78  0.0048      4.8  ADA     -1.1%     BUY
5  2021-09-28 01:00:00   $2.15  $10.94  0.0051      5.1  ADA    -4.45%     BUY